apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: cnas-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-deployer-role
  namespace: cnas-app
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - patch
      - update

  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployer-binding
  namespace: cnas-app
subjects:
  - kind: ServiceAccount
    name: jenkins-deployer
    namespace: cnas-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-deployer-role
