apiVersion: v1
kind: ConfigMap
metadata:
  name: cnas-grafana-datasource
  namespace: monitoring
data:
  prometheus.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: cnas-prometheus
        type: prometheus
        access: proxy
        url: http://cnas-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: 15s
