apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnas-prometheus
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnas-prometheus
rules:
  # Discover Kubernetes nodes
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch

  # Access kubelet metrics through the Kubernetes API server proxy
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnas-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnas-prometheus
subjects:
  - kind: ServiceAccount
    name: cnas-prometheus
    namespace: monitoring

